.TH "deprecated" 3 "Fri Feb 18 2022" "libcpuid" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBGlobal \fBcpu_id_t::l1_assoc\fP \fP" 1c
replaced by \fBcpu_id_t::l1_data_assoc\fP  
.IP "\fBGlobal \fBcpu_id_t::l1_cacheline\fP \fP" 1c
replaced by \fBcpu_id_t::l1_data_cacheline\fP 
.PP

