.TH "feature_map_t" 3 "Fri Feb 18 2022" "libcpuid" \" -*- nroff -*-
.ad l
.nh
.SH NAME
feature_map_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBbit\fP"
.br
.ti -1c
.RI "\fBcpu_feature_t\fP \fBfeature\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libcpuid from the source code\&.
