.TH "internal_id_info_t" 3 "Fri Feb 18 2022" "libcpuid" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal_id_info_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   amd_code_t \fBamd\fP"
.br
.ti -1c
.RI "   intel_code_t \fBintel\fP"
.br
.ti -1c
.RI "} \fBcode\fP"
.br
.ti -1c
.RI "uint64_t \fBbits\fP"
.br
.ti -1c
.RI "int \fBscore\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libcpuid from the source code\&.
