.TH "match_entry_t" 3 "Fri Feb 18 2022" "libcpuid" \" -*- nroff -*-
.ad l
.nh
.SH NAME
match_entry_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfamily\fP"
.br
.ti -1c
.RI "int \fBmodel\fP"
.br
.ti -1c
.RI "int \fBstepping\fP"
.br
.ti -1c
.RI "int \fBext_family\fP"
.br
.ti -1c
.RI "int \fBext_model\fP"
.br
.ti -1c
.RI "int \fBncores\fP"
.br
.ti -1c
.RI "int \fBl2cache\fP"
.br
.ti -1c
.RI "int \fBl3cache\fP"
.br
.ti -1c
.RI "int \fBbrand_code\fP"
.br
.ti -1c
.RI "uint64_t \fBmodel_bits\fP"
.br
.ti -1c
.RI "int \fBmodel_code\fP"
.br
.ti -1c
.RI "char \fBname\fP [32]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libcpuid from the source code\&.
